import Head from 'next/head'
import Image from 'next/image'
import Header from '../../components/header'
import { BodyLarge, BodyMedium, BodySmall, Title1, Title2, Title3 } from '../../components/typography'
import StartScreen from '../../sections/startScreen'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link
                    rel='icon'
                    href='/favicon.ico'
                />
            </Head>
            <main className='main'>
                <StartScreen />
            </main>
        </>
    )
}
